use secrecy::SecretString;

use crate::DandanCredentials;

#[derive(Clone, Copy)]
struct ObfuscatedValue {
    ciphertext: &'static [u8],
    mask: &'static [u8],
}

include!(concat!(env!("OUT_DIR"), "/bundled_credentials.rs"));

/// Returns credentials injected by a trusted release build, if present.
///
/// The generated byte masks keep the plaintext out of source control and out
/// of basic binary string scans. They are obfuscation, not a security boundary:
/// a determined user can still recover credentials from a client executable.
pub fn bundled_credentials() -> Option<DandanCredentials> {
    let app_id = decode(BUNDLED_APP_ID?)?;
    let app_secret = decode(BUNDLED_APP_SECRET?)?;
    Some(DandanCredentials::new(
        app_id,
        SecretString::from(app_secret),
    ))
}

pub fn bundled_credentials_available() -> bool {
    BUNDLED_APP_ID.is_some() && BUNDLED_APP_SECRET.is_some()
}

fn decode(value: ObfuscatedValue) -> Option<String> {
    if value.ciphertext.len() != value.mask.len() {
        return None;
    }
    let plaintext = value
        .ciphertext
        .iter()
        .zip(value.mask)
        .map(|(byte, mask)| byte ^ mask)
        .collect();
    String::from_utf8(plaintext).ok()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn decodes_an_obfuscated_value() {
        assert_eq!(
            decode(ObfuscatedValue {
                ciphertext: &[0x69, 0x67],
                mask: &[0x08, 0x05],
            }),
            Some("ab".to_owned())
        );
    }
}
