[package]
name = "yanami-performance-probe"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
chrono.workspace = true
pinyin.workspace = true
secrecy.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
tokio.workspace = true
unicode-casefold.workspace = true
unicode-normalization.workspace = true
url.workspace = true
uuid.workspace = true
yanami-core = { path = "../yanami-core" }
yanami-emby = { path = "../yanami-emby" }
yanami-storage = { path = "../yanami-storage" }

[lints]
workspace = true
